### ISSUE TITLE
OE pro Mitarbeiter

### ISSUE THREAD

**Issue by surech** [SchweizerischeBundesbahnen/roterOktober-client#15]
Als Benutzer will ich pro Mitarbeiter die Organisationseinheit angeben können. Die OE soll nicht einfach als String wie "IT-SWE-CD3-JV6" abgelegt werden, sondern in einer auswertbaren Form.

**Comment by kreuzerk** [comment]
Mit dem Branch feature/stu/oe-zu-mitarbeiter-erfassen umgesetzt
