### ISSUE TITLE
Mehrere Pensen zu einem Einsatz erfassen

### ISSUE THREAD

**Issue by surech** [SchweizerischeBundesbahnen/roterOktober-client#20]
Als Teamleiter will ich zu einem Einsatz mehrere Pensen erfassen können.
Szenario: Ein Mitarbeiter ist bis am 31.09.2016 zu 80% im Projekt. Im Monat Oktober nur noch zu 50% und bis Ende Jahr noch zu 20%. Er hat zum gleichen Einsatz also drei Pensen mit unterschiedlicher Prozentzahl und verschiedener Laufdauer. Diese will der Teamleiter in der Übersicht auf einer Zeile sehen.

**Comment by kreuzerk** [comment]
Mit dem Branch feature/kk/anzeigeMehrererPensen umgesetzt
