### ISSUE TITLE
Suche nach Mitarbeitern

### ISSUE THREAD

**Issue by surech** [SchweizerischeBundesbahnen/roterOktober-client#22]
Als Teamleiter will ich die Mitarbeiter nach OE und Projekt suchen können.

Todo Backend:
* Auf dem Mitarbeiter die OE als Feld hinzufügen
* REST-Schnittstelle um Suche erweitern

Todo Frontend:
* OE auf dem Mitarbeiter erfassen
* Suche umsetzen

**Comment by kreuzerk** [comment]
Mit dem Filter von feature/kk/addSearchBox kann nach dem Mitarbeiter gesucht werden.
